# == Class: kafka
#
# Used to setup, install and intialize a Kafka broker
#
class kafka (
  $app_log_dir                                    = $::kafka::params::app_log_dir,
  $auto_create_topics_enable                      = $::kafka::params::auto_create_topics_enable,
  $auto_leader_rebalance_enable                   = $::kafka::params::auto_leader_rebalance_enable,
  $background_threads                             = $::kafka::params::background_threads,
  $broker_id                                      = $::kafka::params::broker_id,
  $conf_dir                                       = $::kafka::params::conf_dir,
  $controlled_shutdown_enable                     = $::kafka::params::controlled_shutdown_enable,
  $controlled_shutdown_max_retries                = $::kafka::params::controlled_shutdown_max_retries,
  $controlled_shutdown_retry_backoff_ms           = $::kafka::params::controlled_shutdown_retry_backoff_ms,
  $controller_message_queue_size                  = $::kafka::params::controller_message_queue_size,
  $controller_socket_timeout_ms                   = $::kafka::params::controller_socket_timeout_ms,
  $default_replication_factor                     = $::kafka::params::default_replication_factor,
  $delete_topic_enable                            = $::kafka::params::delete_topic_enable,
  $fetch_purgatory_purge_interval_requests        = $::kafka::params::fetch_purgatory_purge_interval_requests,
  $install_java                                   = $::kafka::params::install_java,
  $install_service                                = $::kafka::params::install_service,
  $java_package                                   = $::kafka::params::java_package,
  $jmx_opts                                       = $::kafka::params::jmx_opts,
  $jvm_heap_mem                                   = $::kafka::params::jvm_heap_mem,
  $jvm_perf_opts                                  = $::kafka::params::jvm_perf_opts,
  $leader_imbalance_check_interval_seconds        = $::kafka::params::leader_imbalance_check_interval_seconds,
  $leader_imbalance_per_broker_percentage         = $::kafka::params::leader_imbalance_per_broker_percentage,
  $log_cleaner_backoff_ms                         = $::kafka::params::log_cleaner_backoff_ms,
  $log_cleaner_dedupe_buffer_size                 = $::kafka::params::log_cleaner_dedupe_buffer_size,
  $log_cleaner_delete_retention_ms                = $::kafka::params::log_cleaner_delete_retention_ms,
  $log_cleaner_enable                             = $::kafka::params::log_cleaner_enable,
  $log_cleaner_io_buffer_load_factor              = $::kafka::params::log_cleaner_io_buffer_load_factor,
  $log_cleaner_io_buffer_size                     = $::kafka::params::log_cleaner_io_buffer_size,
  $log_cleaner_min_cleanable_ratio                = $::kafka::params::log_cleaner_min_cleanable_ratio,
  $log_cleaner_threads                            = $::kafka::params::log_cleaner_threads,
  $log_cleanup_policy                             = $::kafka::params::log_cleanup_policy,
  $log_dirs                                       = $::kafka::params::log_dirs,
  $log_flush_interval_messages                    = $::kafka::params::log_flush_interval_messages,
  $log_flush_interval_ms                          = $::kafka::params::log_flush_interval_ms,
  $log_flush_offset_checkpoint_interval_ms        = $::kafka::params::log_flush_offset_checkpoint_interval_ms,
  $log_flush_scheduler_interval_ms                = $::kafka::params::log_flush_scheduler_interval_ms,
  $log_index_interval_bytes                       = $::kafka::params::log_index_interval_bytes,
  $log_index_size_max_bytes                       = $::kafka::params::log_index_size_max_bytes,
  $log_retention_bytes                            = $::kafka::params::log_retention_bytes,
  $log_retention_check_interval_ms                = $::kafka::params::log_retention_check_interval_ms,
  $log_retention_hours                            = $::kafka::params::log_retention_hours,
  $log_retention_minutes                          = $::kafka::params::log_retention_minutes,
  $log_roll_hours                                 = $::kafka::params::log_roll_hours,
  $log_segment_bytes                              = $::kafka::params::log_segment_bytes,
  $log4j_opts                                     = $::kafka::params::log4j_opts,
  $manage_repo                                    = $::kafka::params::manage_repo,
  $manage_service                                 = $::kafka::params::manage_service,
  $max_nofiles                                    = $::kafka::params::max_nofiles,
  $message_max_bytes                              = $::kafka::params::message_max_bytes,
  $num_io_threads                                 = $::kafka::params::num_io_threads,
  $num_network_threads                            = $::kafka::params::num_network_threads,
  $num_partitions                                 = $::kafka::params::num_partitions,
  $num_recovery_threads_per_data_dir              = $::kafka::params::num_recovery_threads_per_data_dir,
  $num_replica_fetchers                           = $::kafka::params::num_replica_fetchers,
  $offset_metadata_max_bytes                      = $::kafka::params::offset_metadata_max_bytes,
  $package_name                                   = $::kafka::params::package_name,
  $port                                           = $::kafka::params::port,
  $producer_purgatory_purge_interval_requests     = $::kafka::params::producer_purgatory_purge_interval_requests,
  $queued_max_requests                            = $::kafka::params::queued_max_requests,
  $replica_fetch_max_bytes                        = $::kafka::params::replica_fetch_max_bytes,
  $replica_fetch_min_bytes                        = $::kafka::params::replica_fetch_min_bytes,
  $replica_fetch_wait_max_ms                      = $::kafka::params::replica_fetch_wait_max_ms,
  $replica_high_watermark_checkpoint_interval_ms  = $::kafka::params::replica_high_watermark_checkpoint_interval_ms,
  $replica_lag_time_max_ms                        = $::kafka::params::replica_lag_time_max_ms,
  $replica_socket_receive_buffer_bytes            = $::kafka::params::replica_socket_receive_buffer_bytes,
  $replica_socket_timeout_ms                      = $::kafka::params::replica_socket_timeout_ms,
  $repodescr                                      = $::kafka::params::repodescr,
  $reponame                                       = $::kafka::params::reponame,
  $repourl                                        = $::kafka::params::repourl,
  $restart_on_change                              = $::kafka::params::restart_on_change,
  $service_name                                   = $::kafka::params::service_name,
  $socket_receive_buffer_bytes                    = $::kafka::params::socket_receive_buffer_bytes,
  $socket_request_max_bytes                       = $::kafka::params::socket_request_max_bytes,
  $socket_send_buffer_bytes                       = $::kafka::params::socket_send_buffer_bytes,
  $zookeeper_connect                              = $::kafka::params::zookeeper_connect,
  $zookeeper_connection_timeout_ms                = $::kafka::params::zookeeper_connection_timeout_ms,
  $zookeeper_session_timeout_ms                   = $::kafka::params::zookeeper_session_timeout_ms,
  $zookeeper_sync_time_ms                         = $::kafka::params::zookeeper_sync_time_ms
) {

  class { '::kafka::install': } ->
  class { '::kafka::config': } ->
  class { '::kafka::service': } ->
  Class['::kafka']
}
